name: CI

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Test & Build for ${{ matrix.targetPlatform }} with Unity ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.12f1
        targetPlatform:
          - iOS
          - WebGL
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      - uses: webbertakken/unity-test-runner@v1.6
        id: testRunner
        with:
          testMode: playmode #There are no editMode tests yet
          unityVersion: ${{ matrix.unityVersion }}

      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      - uses: webbertakken/unity-builder@v0.15
        with:
          versioning: None
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build