name: CI

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAndBuildForAllPlatforms:
    name: Test & Build for ${{ matrix.targetPlatform }} with Unity ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.12f1
        targetPlatform:
          - iOS
          - WebGL
          - Android
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      - uses: webbertakken/unity-test-runner@v1.6
        id: testRunner
        with:
          testMode: playmode # There are no editMode tests yet
          unityVersion: ${{ matrix.unityVersion }}

      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      - uses: webbertakken/unity-builder@v0.15
        with:
          versioning: None
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: Editor.Builder.BuildProject

      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

  generateIPA:
    name: generate .ipa from iOS project
    runs-on: macOS-latest
    needs: testAndBuildForAllPlatforms
    env:
      BUILDS_PATH: ${{ format('{0}/build', github.workspace) }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/download-artifact@v1
        with:
          name: Build
          path: build
      - run: find $BUILDS_PATH -type f -iname "*.sh" -exec chmod +x {} \; # Fix unity issue with .sh permissions https://issuetracker.unity3d.com/issues/ios-mapfileparser-dot-sh-permission-denied-when-building-xcode-project-built-from-windows-directly-to-a-macos-shared-folder
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'ios buildIpa'